### ISSUE TITLE
Meeting to discuss details

### ISSUE THREAD

**Issue by AlexEne** [AlexEne/wasi-native-threads#1]
Setting up this issue as there was quite a bit of interest to discuss the details of how such an API could work.

Main decision points are around having one thread per instance vs multiple threads per instance model (depending on the proposal below):

There is a proposal to extend Wasm to support the multiple threads per instance [here](https://www.researchgate.net/publication/336447205_Weakening_WebAssembly/fulltext/5da12752a6fdcc8fc3491a97/Weakening-WebAssembly.pdf?origin=publication_detail)

Advantages of 1 thread / instance: 
* Requires no change in the instructions supported by the Wasm spec.
* Some VMs already implement variants of this API that we can experiment with already

Disadvantages:
* Since it duplicates the Instance it has issues around sharing of globals (right now they are basically thread-local)
* Things like dlopen work in non-standard ways (dlopen isn't part of the WASI standard so that may be ok for now)

Multiple threads per instance would be the clean way of solving this since it saves memory (due to the instance not being duplicated for N times as each thread gets spawned). So this is the long-term solution.

One good discussion point would be around how we could do this such that it could be forward-compatible with the changes in the Wasm core standard (and what changes would be needed to keep this compatible).

+ any other topics that I've missed and people would want to bring up.

**Comment by npmccallum** [comment]
I'd like to join. Timezone: US Eastern

**Comment by sbc100** [comment]
sub

**Comment by kulakowski-wasm** [comment]
I'm interested! George Kulakowski at Fastly, on Pacific time.

**Comment by sbc100** [comment]
@dschuff

**Comment by penzn** [comment]
Petr Penzin (Intel), Pacific Time.

**Comment by abrown** [comment]
@abrown, Pacific; email in profile.

**Comment by conrad-watt** [comment]
I'd like to join! I'm UK-based - email in profile. 5-7pm UK time would work for me any day except Tuesday.

**Comment by AlexEne** [comment]
One open question that's not quite clear to me at this point, and relates to the forward compatibility of this that I'd like to discuss: 
What would it mean to implement "multiple threads per instance" model in the absence of theinstructions presented in the paper. (I am yet to read it).

**Comment by mingqiusun** [comment]
I would like to join. US pacific time.

**Comment by conrad-watt** [comment]
@AlexEne the core language would need to at least be extended with the paper's `shared` annotations for functions, tables, and globals (and certain reference types, if used) to make "multiple threads per instance" work in a way that's feasible for VMs to eventually implement (without wider changes).

The main point is that engines have to manage unsharable (e.g. JS) objects that it wouldn't be safe for concurrent code to touch, so the type system needs a way to declare "this function which we allow to execute on a different thread can't have unsharable objects passed into it".

We wouldn't _strictly_ need to add the `fork` instruction mentioned in the paper, thread creation/dispatching could still be managed by host.

**Comment by jlb6740** [comment]
I would like to join (Intel). US pacific time.

**Comment by penzn** [comment]
I'll try to summarize what we discussed about possible API, please correct me if I got something wrong:

- No full pthread support, mostly limited to fork/join
- Pollyfillable by WebWorkers on the Web
  - Maybe this polyfill can be used in Emscripten for thread support
- Possibly not naming it 'threads', to avoid confusion

A few of us thought getting to a multiple instance API in near future doesn't prevent going to single-instance thread support in more distant future.

**Comment by sbc100** [comment]
Regarding `No full pthread support, mostly limited to fork/join`, I think we can break pthread API into 3 buckets:

1. Stuff we can already build today using the existing threads proposal (atomics+wait+wake). I think this is vast majority of the pthread API.
2. Parts where we need to add new constructs (create/join/etc)
3. Stuff that we consider out of scope (signal handing, obscure/options flags?).

I think (3) is fairly small bucket and the combination of (1) and (2) will give enough coverage to get most pthread-based programs running.  At least that as been our experience in emscripten.

So maybe I would phase is as: "Enough core constructs to build a useful subset of the pthread API"?

**Comment by nchamzn** [comment]
I would like to join please, UK time.

**Comment by AlexEne** [comment]
@kulakowski-wasm I don't know what your email is. I've set up a meeting for Monday at 17:30

I've set up the meeting so you should receive an invite.
I will also try to add Monday some more details in the proposal here to serve as a discussion point (e.g. some initial APIs).

**Comment by kulakowski-wasm** [comment]
***@***.*** ! sorry for not including it originally

**Comment by AlexEne** [comment]
Oh gosh, is this a new github feature to block out email addresses 😆. Just it to me on the bytecode alliance zulip chat :) I have the same name there

**Comment by Amanieu** [comment]
I'd also be interested in joining this meeting. UK time.

**Comment by sbc100** [comment]
My email is sbc at chromium org

**Comment by AlexEne** [comment]
Added both, thanks!

**Comment by sbc100** [comment]
Is there a preferred place where folks want to chat about this proposal?  eg. a zulip or discord channel?

**Comment by abrown** [comment]
How about https://bytecodealliance.zulipchat.com/#narrow/stream/235408-rust-toolchain/topic/Threads?

**Comment by lygstate** [comment]
I am also interested

**Comment by lygstate** [comment]
1 thread / instance (WebWorker) way more like a process than a thread, as different worker doesn't sharing any memory, and between worker, we can use sharedbuffer is something like mmap,
So multiple threads per instance is needed. We can use WebWorker simulate the `process`, and `multiple threads per instance` to simulate process.
About polyfill, is that possible to using https://github.com/WebAssembly/stack-switching to polyfill threads in 
`1 thread / instance (WebWorker)` environment?

**Comment by sbc100** [comment]
Its possible to build a pthread-like abstraction on top of instance-per-thread as long as the Wasm linear memory is shared between all instances.  In this case, the entire "address space" of the program is shared between all instances/threads.

Indeed, that seems to be the direction we are moving at the moment, even if there is a long term plan for shared instances in the future.   The stack switching proposal would might allow something like green threading, but I think folks here are looking for something more than just that.

**Comment by lygstate** [comment]
> Its possible to build a pthread-like abstraction on top of instance-per-thread as long as the Wasm linear memory is shared between all instances. In this case, the entire "address space" of the program is shared between all instances/threads.

`"address space" of the program is shared between all instances/threads` is good, but if this is always true, how to implement fork or create process? Indeed, `process` have the attribute of "address space" isolation.

> 
> Indeed, that seems to be the direction we are moving at the moment, even if there is a long term plan for shared instances in the future. The stack switching proposal would might allow something like green threading, but I think folks here are looking for something more than just that.

**Comment by lygstate** [comment]
> This proposal does not propose to add sub-process creation. Here we are just talking about implementing enough for build a 

I am aware of this, just point out the possible confliction with sub-process creation, maybe I am wrong about that

pthread-like API so support multiple threads sharing an address space.

**Comment by AlexEne** [comment]
@lygstate that's a good mention. I will try to find the sub-process proposal and mention it in the proposal body in case there are similarities.
 
Btw, I'll close this issue in the meantime as the meeting has happened, I've included most of the conclusions in the current text, and further discussion will proceed as usual in the WASI meetings forum: https://github.com/WebAssembly/meetings/tree/main/wasi
